apiVersion: apigeeregistry/v1
kind: API
metadata:
  name: graphql-sample
  labels:
    apihub-lifecycle: production
    apihub-style: apihub-graphql
  annotations:
    apihub-primary-contact: graphql-team@example.com
    apihub-primary-contact-description: GraphQL Team
data:
  displayName: GraphQL Example
  versions:
    - metadata:
        name: v1
        annotations:
          apihub-end-of-life-type: apihub-unknown
      data:
        displayName: v1
        state: production
        specs:
          - metadata:
              name: schemagraphql
            data:
              filename: schema.graphql
              mimeType: application/x.graphql
              sourceURI: https://raw.githubusercontent.com/graphql/swapi-graphql/master/schema.graphql
  artifacts:
    - kind: ReferenceList
      metadata:
        name: apihub-dependencies
      data:
        displayName: ""
        description: Defines a list of dependencies
        references: []
    - kind: ReferenceList
      metadata:
        name: apihub-related
      data:
        displayName: ""
        description: Defines a list of related resources
        references: []
