apiVersion: apigeeregistry/v1
kind: API
metadata:
  name: risksapi
  labels:
    apihub-business-unit: bu-2
    apihub-lifecycle: production
    apihub-style: apihub-openapi
    apihub-target-users: partner
    apihub-team: example
    soccer-club: sao-paulo
  annotations:
    apihub-primary-contact: fulano@example.com
    apihub-primary-contact-description: Fulano
data:
  displayName: ✨ Risks API ✨
  description: Credit score analysis API
  availability: NONE
  recommendedDeployment: prod
  versions:
    - metadata:
        name: "100"
        annotations:
          apihub-end-of-life-date: apihub-unknown
          apihub-end-of-life-type: apihub-confirmed
      data:
        displayName: 1.0.0
        state: retired
        specs:
          - metadata:
              name: risk-1.0.0.yaml
            data:
              filename: risk-1.0.0.yaml
              mimeType: application/x.openapi
              sourceURI: file://./specs/risk-1.0.0.yaml
    - metadata:
        name: 1-0-0
        annotations:
          apihub-end-of-life-type: apihub-unknown
      data:
        displayName: 1.0.0
        state: deprecated
    - metadata:
        name: "101"
        annotations:
          apihub-end-of-life-date: apihub-unknown
      data:
        displayName: 1.0.1
        state: huehue
        specs:
          - metadata:
              name: risk-1.0.1.yaml
              annotations:
                apihub-commit-hash: 1ea4ec70919867a8252a43dc27157e3804ea4416
            data:
              filename: risk-1.0.1.yaml
              mimeType: application/x.openapi
              sourceURI: file://./specs/risk-1.0.1.yaml
    - metadata:
        name: "110"
        annotations:
          apihub-end-of-life-date: apihub-unknown
      data:
        displayName: 1.1.0
        state: huehue
        specs:
          - metadata:
              name: risk-1.1.0.yaml
              annotations:
                apihub-commit-hash: bf16776cf0846e296ad64948db6c38c15306f370
            data:
              filename: risk-1.1.0.yaml
              mimeType: application/x.openapi
              sourceURI: file://./specs/risk-1.1.0.yaml
    - metadata:
        name: "111"
        annotations:
          apihub-end-of-life-type: apihub-unknown
      data:
        displayName: 1.1.1
        state: develop
        specs:
          - metadata:
              name: risk-111yaml
            data:
              filename: risk-1.1.1.yaml
              mimeType: application/x.openapi
              sourceURI: file://./specs/risk-1.1.1.yaml
  deployments:
    - metadata:
        name: dev
        labels:
          apihub-gateway: apihub-google-cloud-apigee
        annotations:
          apihub-external-channel-name: View Docs
      data:
        displayName: dev
        apiSpecRevision: 111/specs/risk-111yaml
        externalChannelURI: https://registry-spec-renderer-65w5mflg4a-rj.a.run.app/render/projects/cabral-apigee/locations/global/apis/risksapi/deployments/dev
    - metadata:
        name: prd
        labels:
          apihub-gateway: apihub-google-cloud-apigee
        annotations:
          apihub-external-channel-name: View Docs
      data:
        displayName: prd
        apiSpecRevision: 101/specs/risk-1.0.1.yaml
        externalChannelURI: https://registry-spec-renderer-65w5mflg4a-rj.a.run.app/render/projects/cabral-apigee/locations/global/apis/risksapi/deployments/prd
  artifacts:
    - kind: ReferenceList
      metadata:
        name: apihub-dependencies
      data:
        displayName: ""
        description: Defines a list of dependencies
        references:
          - id: google-maps
            displayName: Google Maps
            category: apihub-third-party-apis
            resource: ""
            uri: https://developers.google.com/maps/documentation/javascript/reference
    - kind: ReferenceList
      metadata:
        name: apihub-related
      data:
        displayName: ""
        description: Defines a list of related resources
        references: []
